/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaNegocio.ClsConexion;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fundamentos DS
 */
public class WinAgenda extends javax.swing.JFrame {

    /**
     * Creates new form WinAgenda
     */
    ClsConexion base;
    String BasedeDatos;
    String nom,telf;
    int clave;
    public WinAgenda() {
        initComponents();
        ArchBd.setVisible(false);
        PnlContacto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContacto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        BtnNuevo = new javax.swing.JButton();
        BtnConsulta = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiente = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        LblResp = new javax.swing.JLabel();
        ArchBd = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        OpBd = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Agenda (Fundamentos de Desarrollo de Software)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        PnlContacto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, -1));

        jLabel2.setText("Telefono:");
        PnlContacto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        PnlContacto.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 210, -1));
        PnlContacto.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 210, -1));

        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        BtnConsulta.setText("Consultar");
        BtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        BtnAnterior.setText("Anterior");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, -1));

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 90, -1));

        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        PnlContacto.add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 90, -1));
        PnlContacto.add(LblResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 380, 30));

        getContentPane().add(PnlContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 420));

        ArchBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBdActionPerformed(evt);
            }
        });
        getContentPane().add(ArchBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        OpBd.setText("Base de Datos");

        jMenuItem1.setText("Conectar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        OpBd.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        OpBd.add(jMenuItem2);

        jMenuBar1.add(OpBd);

        jMenu2.setText("Contactos");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Ir a la Agenda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArchBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBdActionPerformed
        // TODO add your handling code here:
        File f=ArchBd.getSelectedFile();
        BasedeDatos=f.getAbsolutePath();
        ArchBd.setVisible(false);
        base=new ClsConexion(BasedeDatos);
    }//GEN-LAST:event_ArchBdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ArchBd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        BtnAnterior.setVisible(false);
        BtnSiguiente.setVisible(false);
        this.BtnBorrar.setVisible(false);;
        this.BtnAgregar.setVisible(true);
        this.BtnModificar.setVisible(false);
        TxtNombre.setText(null);
        TxtTelefono.setText(null);
        TxtNombre.setEnabled(true);
        TxtTelefono.setEnabled(true);
        LblResp.setText("Va a ingresar un nuevo registro...");
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TxtNombre.setEnabled(false);
        TxtTelefono.setEnabled(false);
        BtnAnterior.setVisible(false);
        BtnSiguiente.setVisible(false);
        BtnAgregar.setVisible(false);
        BtnModificar.setVisible(false);
        BtnBorrar.setVisible(false);
        PnlContacto.setVisible(true);
       /* PnlProductos.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlDetF.setVisible(false);
        PnlCreFac.setVisible(false);*/
        try {
            // TODO add your handling code here:
            base.consulta("TbAgenda");
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void BtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaActionPerformed
        // TODO add your handling code here:
        BtnAnterior.setVisible(true);
        BtnSiguiente.setVisible(true);
        this.BtnBorrar.setVisible(false);
        this.BtnAgregar.setVisible(false);
        this.BtnModificar.setVisible(false);
        LblResp.setText(null);
    }//GEN-LAST:event_BtnConsultaActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        BtnAnterior.setVisible(false);
        BtnSiguiente.setVisible(false);
        this.BtnBorrar.setVisible(false);
        this.BtnAgregar.setVisible(false);
        this.BtnModificar.setVisible(true);
        TxtNombre.setEnabled(true);
        TxtTelefono.setEnabled(true);
        LblResp.setText("Va a modifcar el registro...");
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        BtnAnterior.setVisible(false);
        BtnSiguiente.setVisible(false);
        this.BtnBorrar.setVisible(true);
        this.BtnAgregar.setVisible(false);
        this.BtnModificar.setVisible(false);
        LblResp.setText("Va a eliminar el registro...");
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            base.anterior();
            TxtNombre.setText(base.registros().getString("nombre"));
            TxtTelefono.setText(base.registros().getString("telefono"));  
             clave = base.registros().getInt("Id_Agenda");  
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            base.siguiente();
            TxtNombre.setText(base.registros().getString("nombre"));
            TxtTelefono.setText(base.registros().getString("telefono"));  
             clave = base.registros().getInt("Id_Agenda");  
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
       nom=TxtNombre.getText();
       telf=TxtTelefono.getText();
        try {
            base.insertarC("TbAgenda",nom,telf);
            TxtNombre.setEnabled(false);
            TxtTelefono.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }       
        LblResp.setText("Ingreso Exitoso...");
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
       nom=TxtNombre.getText();
       telf=TxtTelefono.getText();
        try {
            base.actualizarC("TbAgenda",nom,telf,clave);
            TxtNombre.setEnabled(false);
            TxtTelefono.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }              
        TxtNombre.setEnabled(false);
        TxtTelefono.setEnabled(false);
        LblResp.setText("Se modifico exitosamente...");
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        // TODO add your handling code here:
         try {
            base.eliminarC("TbAgenda", clave);
            
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }       
         LblResp.setText("Se elimino el resitro exitosamente...");
    }//GEN-LAST:event_BtnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBd;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnConsulta;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JLabel LblResp;
    private javax.swing.JMenu OpBd;
    private javax.swing.JPanel PnlContacto;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
